# GoReleaser configuration for clickhouse-schemaflow-visualizer
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: clickhouse-schemaflow-visualizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - static/**/*
      - .env.example

nfpms:
  - id: packages
    package_name: clickhouse-schemaflow-visualizer
    vendor: ChView2
    homepage: https://github.com/FulgerX2007/clickhouse-schemaflow-visualizer
    maintainer: ChView2 Team <maintainer@example.com>
    description: Web-based ClickHouse database viewer and query interface
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - ca-certificates
    scripts:
      preinstall: scripts/preinstall.sh
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
      postremove: scripts/postremove.sh
    contents:
      - src: static
        dst: /usr/share/clickhouse-schemaflow-visualizer/static
        type: tree
        file_info:
          mode: 0644
      - src: .env.example
        dst: /etc/clickhouse-schemaflow-visualizer/config.env.example
        type: config|noreplace
        file_info:
          mode: 0644
    rpm:
      group: Applications/Databases
      summary: Web-based ClickHouse database viewer
    deb:
      lintian_overrides:
        - statically-linked-binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
