
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper-test
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - clickhouse-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-test-engines
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./scripts/clickhouse_test_engines.sql:/docker-entrypoint-initdb.d/clickhouse_test_engines.sql:ro
      - ./config/clickhouse-config.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
    environment:
      - CLICKHOUSE_DB=test_engines
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - KRAFT_CLICKHOUSE_TEST_ENGINES=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - zookeeper
    networks:
      - clickhouse-network

  clickhouse-schemaflow-visualizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickhouse-schemaflow-visualizer
    ports:
      - "8080:8080"
    env_file: ".env"
    restart: unless-stopped
    depends_on:
      - clickhouse
    networks:
      - clickhouse-network

volumes:
  clickhouse-data:
    driver: local

networks:
  clickhouse-network:
    driver: bridge
