name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Extract changelog entry between the current and previous version tags
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ steps.get_version.outputs.VERSION }}^ 2>/dev/null || echo "")
          if [ -n "$PREVIOUS_TAG" ]; then
            changelog="## Changes since $PREVIOUS_TAG\n"
            changelog+="$(git log --pretty=format:"* %s" $PREVIOUS_TAG..${{ steps.get_version.outputs.VERSION }})"
          else
            changelog="## Initial Release\n"
            changelog+="$(git log --pretty=format:"* %s" ${{ steps.get_version.outputs.VERSION }})"
          fi
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo -e "$changelog" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
